project:
  type: website

website:
  title: "Mapping Galvanized"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Roster.qmd

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true